version: 0.2
env:
  variables:
    SQL_FILE: "transaction_runtime.sql"
  secrets-manager:
    ROLE_PASSWORD: "testing/alfa/transaction_runtime_user" # THis is specific for each build job
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands:
            - echo "we are in the pre build phase"
            - export PGPASSWORD=$ROLE_PASSWORD
    build:
        commands:
            - echo "Running SQL file"
            - bash run_sql.sh $SQL_FILE 'database-1.c1lhknn6bc0m.eu-west-2.rds.amazonaws.com' 'postgres' $ROLE_PASSWORD
    post_build:
        commands:
            - echo "we are in the post build phase"