version: 0.2
env:
  secrets-manager:
    ROLE_PASSWORD: "testing/alfa/transaction_runtime_user" # THis is specific for each build job
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands:
            - echo "we are in the pre build phase"
            - export PGPASSWORD=$ROLE_PASSWORD
    build:
        commands:
            - echo "Running SQL file"
            - bash run_sql.sh $ROLE_PASSWORD
    post_build:
        commands:
            - echo "we are in the post build phase"