version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands:
            - echo "we are in the pre build phase"
            - export PGPASSWORD=$ROLE_PASSWORD
    build:
        commands:
            - echo "Running SQL file"
            - bash run_sql.sh $SQL_FILE $HOST $DATABASE $ROLE_PASSWORD
    post_build:
        commands:
            - echo "we are in the post build phase"