version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
            - yum install postgresql -y
    pre_build:
        commands:
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "this is build section inside buildspec.yml file"
            - echo "we will run some tests"
    post_build:
        commands:
            - echo "we are in the post build phase"